### ISSUE TITLE
Poor performance compared to Spring R2DBC (Spring Data Reactive)

### ISSUE THREAD

**Issue by Sgitario** [hibernate/hibernate-reactive#1264]
I've written [an application](https://github.com/Sgitario/frameworks-benchmarks/tree/main/data-reactive-benchmark) that compares one application written in Quarkus using Hibernate Reactive, and another application in Spring using r2dbc, and the performance difference is huge, much worse when using Hibernate Reactive:

![hibernatereactivevsspringreactive](https://user-images.githubusercontent.com/6310047/163320177-5e27834d-c565-4dfb-97b5-8a5f30914b5a.png)

**Note**: This is a throughput benchmark (operations per second), though the numbers are not significant, it does the difference between Quarkus and Spring Boot. 

Versions:
- Quarkus 2.8.0.final (using hibernate reactive 1.1.4.Final)
- Spring Boot 2.6.6
- Java 11

I've attached the [java flight recordings profiles](https://github.com/hibernate/hibernate-reactive/files/8486506/java.flight.recordings.zip) for both Quarkus and Spring apps just in case it helps to find the root cause of the performance difference (ignore the number of exceptions within the profile, this is a known issue when profiling apps in JDK).

## How to run the benchmark
1.- `git clone https://github.com/Sgitario/jcloud-unit`
2.- `cd jcloud-unit`
3.- `mvn clean install -Pframework -DskipTests`
4.- `cd ..`
5.- `git clone https://github.com/Sgitario/frameworks-benchmarks`
6.- `cd frameworks-benchmarks`
7.- `mvn clean install -pl .`
8.- `cd data-reactive-benchmark`
9.- `mvn clean install`

After the last command is finished, you can find the benchmark results in `.../frameworks-benchmarks/data-reactive-benchmark/benchmarks/target/benchmarks-results/ThroughputBenchmarks.json`. (To visualize it, you can upload it to https://jmh.morethan.io/).

The Java Flight Recording can be found in:
- For Quarkus: ../frameworks-benchmarks/data-reactive-benchmark/benchmarks/target/ThroughputBenchmarks/quarkus/profile.jfr
- For Spring: ../frameworks-benchmarks/data-reactive-benchmark/benchmarks/target/ThroughputBenchmarks/spring/profile.jfr

I would say that the problem is in Hibernate Reactive, not in either Panache or Quarkus. However, if I'm wrong, let me know and will create the issue in any of these repos. 

## Benchmark for Hibernate Classic vs Spring Boot Data

I've also compared Hibernate Classic and Spring Boot Data, and here, the performance is much better when using Quarkus and Hibernate Classic:

![hibernateclassicvsspringdata](https://user-images.githubusercontent.com/6310047/163322044-89c79179-eef4-4f80-a1d9-044cd841763f.png)

**Comment by DavideD** [comment]
@Sanne, maybe you can comment on this?

**Comment by Sanne** [comment]
Very interesting, thanks @Sgitario ! I'll need to have a look.

**Comment by DavideD** [comment]
I'm going to close this issue for now. @Sanne can add more details about the test in general when he has time.

What I can say is that you cannot compare the `deleteById` Panache is doing with a simple `delete from table` query.
The reason is that Panache needs some extra steps because it will make sure to delete associated entities if the mapping requires it. I think we could do better by realizing in advance that there are no associations mapped and that there is no need to throw an exception when deleting an entity that's not on the db (this is an implementation detail). But I don't think we have the time to focus on this at the moment.

That said, if the `deleteById` becomes a bottleneck, it's possible to replace it with an HQL query (or even a native query) instead of using the `deleteById` in Panache.

**Comment by Sanne** [comment]
right, thanks @DavideD .

@Sgitario another problem I've noticed is that JMH is best suited for "microbenchmarks": measuring efficiency of very small pieces of code. It might be used in this case as well, but you should use a much longer warmup time (it takes much longer to "warmup" a full application stack than a single method), and ensure you're measuring a larger portion of time.

This is particularly true in this benchmark: when opening the JFR recordings you provided, I see significant locking times spent on some internal datastructures in the Jackson library; that got my attention as I wouldn't expect a widely used, reliably library like Jackson to manifest a contention bottleneck on an hot path, and indeed I found that this lock is only obtained during bootstrap.

Which means the numbers are skewed; would be nice to see if you can adapt the timings to avoid capturing any bootstrap overhead.

Also interesting: both Spring and Quarkus are affected negatively by the same lock as they both use Jackson; but the timings of the contention is much higher in Quarkus as it's starting more threads by default - none of these being able to make progress.
So actually both frameworks should improve throughput.

Some other things that should be done to compare apples to apples:
 - Disable context propagation in Quarkus (it's heavy and you don't need it - it's an extra feature which Spring doesn't provide)
 - Implement both deletion routines to provide the same semantics
 - They use different OOB defaults; could be interesting to normalize them (Quarkus defaults to more threads, Spring also uses the netty-native extension by default, which is optional in Quarkus as we believe it should be opt-in since it's not going to work in all environments).

**Comment by Sanne** [comment]
BTW while we closed this particular issue as I believe the "poor performance" is yet to be proven, I'd be totally happy to see more of these and/or help you with the benchmark.
If you have upcoming changes to the benchmark I'd be glad to review them; I might send you a PR myself to show how to best disable context propagation.

**Comment by Sgitario** [comment]
Many thanks @Sanne ! I will update the benchmark to set up better warmup times. 

For the benchmark project, the idea was to use the default configuration by Spring Boot/Quarkus (as it's likely what users will do) for the same use cases and compare how each runtime performance is in comparison to the other. I see JMH is not designed for such a purpose, but what I'm looking for it's the difference among runtimes, not numbers. 

As far as I know, the context propagation issue in Quarkus is known and in spite of being complex to resolve, eventually it will be sorted out.
About the performance issue of deletions in Panache reactive, as long as the Panache team is aware of it, I guess it's ok. 
In any case, this issue should not belong to the Hibernate reactive repo. 
Thank you both for taking a look at this!

**Comment by Sgitario** [comment]
FYI: After updating the benchmark with better warmup times and not including the delete action within the benchmark, the benchmark times for Quarkus and Spring Boot are pretty much the same.

**Comment by Sanne** [comment]
Excellent, glad to hear!

However based on my other testing activities I would expect Hibernate Reactive to beat competition. I suppose you didn't disable CP in this test?

**Comment by Sgitario** [comment]
> Excellent, glad to hear!
> 
> However based on my other testing activities I would expect Hibernate Reactive to beat competition. I suppose you didn't disable CP in this test?

I didn't because I didn't want to tune any of the Quarkus/Spring Boot applications. 
But to showcase purposes, I would be happy to try it out. Any hints about how to disable it?

**Comment by Sanne** [comment]
Sure :)

It's a bit inconvenient currently, but this is the recipe; you need to do BOTH of:

1# adding these to the configuration properties

```

mp.context.ThreadContext.propagated=None
mp.context.ThreadContext.cleared=None
mp.context.ThreadContext.unchanged=Remaining
```

AND

2# Disable it via annotations on each REST endpoint:

```
    @GET
    @CurrentThreadContext(propagated = {}, cleared = {}, unchanged = ThreadContext.ALL_REMAINING)
    public Striong hello() {
        ...
```

> I didn't because I didn't want to tune any of the Quarkus/Spring Boot applications.

+1 that's fair. We should really fix this OOB, but it's interesting to see where it could get us as soon as that's done :)
