### ISSUE TITLE
how Hibernate reactive work

### ISSUE THREAD

**Issue by HelloTo4x** [hibernate/hibernate-reactive#1280]
Hi, I am confused by this problem. Hibernate use JDBC, and JDBC is Blocking I/O, how hibernate reactive can work with JDBC, and how Hibernate reactive can handle Transaction. thanks

**Comment by DavideD** [comment]
Hibernate ORM uses JDBC but Hibernate Reactive doesn't.
Hibernate Reactive connects to the databases using the [Vert.x SQL clients](https://vertx.io/docs/#databases).

**Comment by HelloTo4x** [comment]
@DavideD so how does Hibernate Reactive work, which library is it based on ?

**Comment by DavideD** [comment]
It's built on top of Hibernate ORM.

We have added a new APIs but we try to reuse as much as we can for the implementation (the dialects for example).
You can see in the source code that we extend several existing classes in ORM but we add new methods or override existing ones when we need to so that we can pass CompletionStage objects around.

Because we are using Vert.x,  we can have a non blocking API all the way.

**Comment by gavinking** [comment]
> so how does Hibernate Reactive work, which library is it based on ?

The very first section of the documentation explains that:

> Java persistence frameworks like JDBC, JPA and Hibernate ORM were designed to use blocking IO for interaction with the database, and are therefore not appropriate for use in a reactive environment. As far as we know, Hibernate Reactive is the first true ORM implementation designed to take advantage of non-blocking database clients. Out of the box, the Vert.x clients for PostgreSQL, MySQL, and DB2 are supported, though the architecture is not limited to these drivers.

<https://hibernate.org/reactive/documentation/1.1/reference/html_single/#preface>
