### ISSUE TITLE
Investigate switching to Oracle DB container image: 21-slim-faststart flavour

### ISSUE THREAD

**Issue by blafond** [hibernate/hibernate-reactive#1383]
Quarkus has made the switch to improve bootstrapping.  See this [PR](https://github.com/quarkusio/quarkus/pull/27588) for details

<oracle.image>docker.io/gvenzl/oracle-xe:21-slim</oracle.image>

**Comment by blafond** [comment]
@DavideD  Ran `clean build` locally multiple times with both oracle versions I get basically the same results for either one.   ~2 minutes.

Are there more specific metrics or ways could track?

**Comment by DavideD** [comment]
That's fine, I was expecting something similar because we only start the server once.

I've tried it on my machine:
```
gvenzl/oracle-xe:21.3.0-slim 
-- with image download:  BUILD SUCCESSFUL in 4m 14s
-- already downloaded :  BUILD SUCCESSFUL in 1m 27s

gvenzl/oracle-xe:21.3.0-faststart
-- with image download: BUILD SUCCESSFUL in 7m 41s 
-- already downloaded : BUILD SUCCESSFUL in 1m 15s 
``` 

The build was slightly faster when the image is available but downloading the new image was quite slow. 
Not that this is a rigorous indication but I think we can continue to use the slim version for now.

Maybe there's a difference when running it on slower machines. We can reconsider this later.

Thanks
