### ISSUE TITLE
Wrong support for URI

### ISSUE THREAD

**Issue by florent-lb** [hibernate/hibernate-reactive#1425]
Hi Hibernate ! 

I worked with Hibernate Reactive to introduce it in my client's spring boot environment. But the OPS team in my client use an api to generate URL DB. Theses url contains _  (underscore). Using _ will never be a problem with "standard" hibernate, I use these url today without any issue but you choose to use URI instead of URL and URI doesn't support underscore.

The problem is  [here : DefaultSqlClientPoolConfiguration](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java#L93) 

Example value (anything with _) : jdbc:postgresql://my_db:5432.com/my_schema

URI doesn't throw any error but the value Host & port stay null and authority is fill instead. but DefaultSqlClientPoolConfiguration (L 111) : 

[link](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java#L109)

`
 String host = scheme.equals("oracle")
                ? oracleHost(uri)
                : uri.getHost();
`

[link](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java#L113)
`
        int port = scheme.equals("oracle")
                ? oraclePort(uri)
                : uri.getPort();
`

Try to read only getHost() and getPort()

This problem doesn't occurs with URL, but URL doesn't support all scheme like URI. 
But URI must support _ (https://www.rfc-editor.org/rfc/rfc3986#section-2.3), I'll try to replace URI with %5F but still broken. 

Replace by ipv4 adresse == no problem

Problem follow here in OpenJDK : https://bugs.openjdk.org/browse/JDK-8291591

But today is a regression comparing to Hibernate  "standard". And Without dns name I can't go to production with Hibernate Reactive today :'( 

For more in formation : 

Hibernate version : 
org.hibernate.reactive:hibernate-reactive-core:1.1.9.Final

**Comment by DavideD** [comment]
Thanks, it seems like a bug and we will have to revisit that method.

As a workaround, you can register your own `SqlClientPoolConfiguration` implementation and return a valid `SqlConnectOptions`. Basically, you have to override `DefaultSqlClientPoolConfiguration#connectOptions(URI uri)`.

We describe how to do it for the `VertxInstace` in this part of the documentation, but the process is the same for `SqlClientPoolConfiguration`.

**Comment by DavideD** [comment]
@blafond, would you have time to look into this?e

**Comment by florent-lb** [comment]
Thank for the link sharing I look that asap.

**Comment by blafond** [comment]
Looking at it

**Comment by DavideD** [comment]
Thanks

**Comment by blafond** [comment]
I've written a simple test that calls `new DefaultSqlClientPoolConfiguration().connectOptions( "jdbc:postgresql://my_db:5432.com/my_schema" );` and I get the same error and removing the `jdbc:` segment the test works.

In all of our current tests that require a connection a `DefaultSqlCientPool` is used to convert a URL into a URI via the static [parse( String url)](https://github.com/hibernate/hibernate-reactive/blob/dc13463b4cac5ce07f28f94f929a563cdcce5d0c/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPool.java#L249) method.

In our reactive world the URI's **scheme** is expected to be `jdbc:` and we currently remove that from the configuration properties.

**Comment by DavideD** [comment]
We've decided some time ago to accept JDBC as configuration even if underneath we are not using JDBC so that people could use the same URL they would use for ORM. Also, I think we expected the Vert.x SQL client to reuse the same syntax (this is not actually the case). We in the decided to make the jdbc part optional considering that jdbc is not actually used (it would be nice in the future to allow the use of the vert.x syntax, but that's for another issue).

It think the best approach for this issue is to add a test in [JdbcUrlParserTest](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/test/java/org/hibernate/reactive/configuration/JdbcUrlParserTest.java#L32) that uses `my_host` as localhsot (maybe other values as well). And test that the resulting `SqlConnectOptions` object contains the correct info.

Then we have to figure out if there's a different way to parse the url string that doesn't exclude values in [DefaultSqlClientPoolConfiguration#connectOptions](https://github.com/hibernate/hibernate-reactive/blob/dc13463b4cac5ce07f28f94f929a563cdcce5d0c/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/DefaultSqlClientPoolConfiguration.java#L93). I think we can get the whole string url using `Uri.toString()`, so we might not need to change all parameters but I'm not sure.

@blafond Does this help?

**Comment by gavinking** [comment]
> We've decided some time ago to accept JDBC as configuration even if underneath we are not using JDBC so that people could use the same URL they would use for ORM. 

I still think this is a good idea. Hibernate users already know this syntax, and it lets them easily copy/paste config between the two things.

**Comment by DavideD** [comment]
It seems to work fine and I'm not against it.
But I would like to also support the vert.x syntax using the `vertx:` prefix.

It would be less work for use and It would also be a nice fallback for cases like this.

**Comment by DavideD** [comment]
One thing that we are doing right now is trying to parse any possible jdbc url, it would probably be easier to identify the dialect first and then parse the url accordingly.
