### ISSUE TITLE
Add DB2 SQL for the creation of user and db for test

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#145]

**Comment by DavideD** [comment]
@aguibert Can you have a look at this, please? I'm not sure how to connect to db2

**Comment by aguibert** [comment]
@DavideD I assume you mean from a manual (non-container) install of DB2? TBH I'm not sure either, I've only ever used DB2 from the container. Non-container DB2 installs aren't very easy to get, so I assume that the set of users who A) have a manual DB2 install and B) don't already know how to create a DB/user on it is going to be very small or non-existant.

**Comment by gavinking** [comment]
If I understand correctly, you can't actually create users in DB2 SQL. DB2 users are OS users that you grant permissions on DB2 tables.

Honestly I think it's perfectly fine if we just assume that testing on DB2 means using `-Pdocker`. The Docker stuff that Andrew set up actually works *really* well and it's easier to install Docker locally than it is to install DB2 (if I recall correctly from years ago, installing DB2 is actually quite painful, though perhaps it's got better).

Anyway, I don't think we need to have this information in the README. It makes sense to have it for MySQL and Postgres because they're both *so* easy to install and run, but DB2 is a different sort of beast.

I would just close this issue.
