### ISSUE TITLE
Document how to replace the SqlClientPool using services

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#157]
Now that we have https://github.com/hibernate/hibernate-reactive/pull/155 we need to remember to add an explanation with example on how to do that in the documentation (When we start to work on one)

**Comment by gavinking** [comment]
Yes, I agree, but perhaps we need to be a little bit careful about that because I'm not sure that the `ReactiveConnection` interface is 100% cooked. In principle, future changes to it could break user code.

So I was thinking of leaving it undocumented for now, and just having it there so that people who ask for it explicitly can be pointed to it with a big caveat that they should not rely on it not breaking.

**Comment by DavideD** [comment]
Sounds good. It's not something we need immediately. 

ORM uses some annotation to highlight features that are quite experimental and might change in the future. We can introduce something similar.

I will just keep the issue as a reminder for when we release the first final.
I would like to have at least a test for this at some point.

**Comment by gavinking** [comment]
> ORM uses some annotation to highlight features that are quite experimental and might change in the future. We can introduce something similar.

That sounds like a good idea.

But why can't we just use the same annotations? We already have a hard dependency on Hibernate ORM.

**Comment by DavideD** [comment]
Yes, of course :)
The annotation is [@Incubating](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/Incubating.java)

**Comment by gavinking** [comment]
@DavideD would you consider it sufficient documentation that this is described in the Javadoc for `ReactiveConnectionPool`, including a code example?

**Comment by DavideD** [comment]
ok

**Comment by gavinking** [comment]
> ok

soooo .... does that mean we can close this? :-)
