### ISSUE TITLE
remove ReactiveSettings.VERTX_POOL

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#170]
We now have a defined way to integrate custom `ReactiveConnectionPool`s, so just as soon as I get the OK from @aguibert, I want to remove the `VERTX_POOL` setting and the code that uses it.

**Comment by aguibert** [comment]
hmm, this was the approach I was planning to use in Quarkus. So the replacement is to implement and register a custom `StandardServiceInitiator<ReactiveConnectionPool>`?  Do we expect that end-users will ever want do this? From a user-perspective I think it's easier to just put your Vertx `Pool` in the config map using the predefined key, rather than creating/registering a whole new class.

**Comment by gavinking** [comment]
> So the replacement is to implement and register a custom `StandardServiceInitiator<ReactiveConnectionPool>`?

```java
 new StandardServiceRegistryBuilder()
      .applySettings( properties )
      .addService( ReactiveConnectionPool.class, new SqlClientPool() {
           @Override
	   public void start() { 
                //your code goes here
           }
      } )
      .build();
```

I believe.

> Do we expect that end-users will ever want do this?

Yes, potentially.

>  From a user-perspective I think it's easier to just put your Vertx `Pool` in the config map using the predefined key, rather than creating/registering a whole new class.

But this doesn't let you use a different sort of database driver, or implement any sort of custom strategy for managing connections. So it's *much* less powerful.

**Comment by gavinking** [comment]
@aguibert note that you can totally just take that code I want to delete and copy/paste it into the `//your code goes here` bit

**Comment by gavinking** [comment]
It's documented [here](https://github.com/hibernate/hibernate-reactive/blob/1fcb8d370ad075b36900898528bfdaf86b97fb71/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnectionPool.java#L21) FTR.

**Comment by aguibert** [comment]
> But this doesn't let you use a different sort of database driver, 

When you pass in a Vertx Pool directly then Hibernate has no need to search for a Vertx driver on its own. Driver resolution is only used for constructing a pool instance.

> or implement any sort of custom strategy for managing connections. So it's much less powerful.

This is potentially important, but I can't think of what sort of custom strategies might be needed? A custom connection pool impl perhaps?

**Comment by Sanne** [comment]
> From a user-perspective I think it's easier to just put your Vertx `Pool` in the config map using the predefined key, rather than creating/registering a whole new class.

Remember you're not registering a _class_ , you can pass in the instance.

Grab a reference to the existing objects which are managed by Quarkus, inject them. No need to "start" them or otherwise initialize them later; of course you _might_ want to initialialize them later.

For exampl, I expect the passed in implementation to perform an `ArC` lookup, as we're building this registry during the build - while the connection pools are created only at boot time (definitely later, even possibly on a different JVM and different machine).

**Comment by Sanne** [comment]
To clarify my previous comment: 

conceptually it's very similar to "just put your Vertx Pool in the config map" - I belive it's simpler though, simpler code to boot it fast, and no need to use generic properties. 

Also, I can see a problem with serialization of that reference.. remember the "config map" will need to prune such objects from the heap before we can safely take a snapshot to build the native-image constants.

**Comment by gavinking** [comment]
> Driver resolution is only used for constructing a pool instance.

What I'm saying is that this is useful for integrating stuff that's *not* a Vert.x `Pool` at all.

> Remember you're not registering a class, you can pass in the instance.

Exactly, that's what I was trying to show with my code snippet above.
