### ISSUE TITLE
Remove all the System.out.println and use proper logging

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#172]

**Comment by gavinking** [comment]
There's only two `System.out.println()`s in the whole codebase.

1. Our support for `hibernate.show_sql`, which has always used `System.out.println()`. We don't need to change that.
2. And the error logger for when a `drop` fails during schema export. (A completely ignorable error.)

I agree we should change the second one, because I never want to see those errors. Log it at debug level, preferably.

**Comment by gavinking** [comment]
I've added support for SQL statement logging via the traditional log category `org.hibernate.SQL`.

We can close this now, since there's actually no `println()` anywhere except for the support for `hibernate.show_sql`.
