### ISSUE TITLE
 How to initialize a collection in a collection?

### ISSUE THREAD

**Issue by kfgisbis** [hibernate/hibernate-reactive#1728]
sessionFactory.withSession(session ->
                        session.find(Entity.class, id)
                                .call(ent-> session.fetch(ent.getGroup())))

and groups have other collections, how to initialize them?

**Comment by DavideD** [comment]
The Hibernate ORM documentation has a chapter related to how you can fetch associations for this scenario using queries or  Graphs: [11. Fetching](https://docs.jboss.org/hibernate/orm/6.3/userguide/html_single/Hibernate_User_Guide.html#fetching)

These are the recommended approaches because they reduce the amount of queries to the database.

That said, if you are interested in how to do this with the `.fetch` method, this is one way:
```java
sessionFactory.withSession(session ->session
    .find(Entity.class, id)
    // I'm assuming that this is a one-to-many
    .call(ent-> session.fetch(ent.getGroup()).call(this::fetchAssociation))
)

private Uni<Void> fetchAssociation(List<Group> books) {
	Uni<Void> result = Uni.createFrom().voidItem();
		for ( Book book : books ) {
			result = result.call( () -> Mutiny.fetch( book.something) );
		}
		return result;
	}
```

But this approach will run a query for each element of the list. It's usually not recommended.
I'm closing this issue, but feel free to ask more questions if you have some doubts.

**Comment by DavideD** [comment]
You could also use `Multi`: https://github.com/hibernate/hibernate-reactive/issues/1416#issuecomment-1299729972

**Comment by kfgisbis** [comment]
Thank you very much, that makes a lot of things easier!
