### ISSUE TITLE
Upsert only works for PostgreSQL

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#1768]
Related to PR  https://github.com/hibernate/hibernate-reactive/pull/1765

We added an upsert method to the stateless session interfaces in Hibernate Reactive.
For example in [Mutiny.StatelessSession#upsert](https://github.com/hibernate/hibernate-reactive/blob/1b0ec2be834bcdeadd8106dc560514e10b45548d/hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/Mutiny.java#L1747).

The problem is that it seems to only work for PostgreSQL.
The [test](https://github.com/hibernate/hibernate-reactive/blob/1b0ec2be834bcdeadd8106dc560514e10b45548d/hibernate-reactive-core/src/test/java/org/hibernate/reactive/UpsertTest.java#L39) fails for the other databases because when it looks for the results in the db, it returns an empty list.

I've quickly checked the same test with Hibernate ORM and MySQL, and it seems to run different queries. Probably, not all databases support the operation.  But we need to look into it.

**Comment by blafond** [comment]
@DavideD upsert() works for PostgreSQL because `reactiveMerge()` is actually called and executes this SQL:
`merge into Record as t using (select cast($1 as bigint) id, cast($2 as text) message) as s on (t.id=s.id) when not matched then insert (id, message) values (s.id, s.message)  when matched then update set message=s.message`


The PG DB test creates a `MutationExecutor` of type [`ReactiveMutationExecutorSingleBatched`](https://github.com/hibernate/hibernate-reactive/blob/1b0ec2be834bcdeadd8106dc560514e10b45548d/hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/ReactiveStandardMutationExecutorService.java#L88) which kicks off the update/merge.

Other DB's create a `MutationExecutor` of type [`ReactiveMutationExecutorSingleSelfExecuting`](https://github.com/hibernate/hibernate-reactive/blob/1b0ec2be834bcdeadd8106dc560514e10b45548d/hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/ReactiveStandardMutationExecutorService.java#L76) which ends up calling the [default performReactiveNonBatchedOperations()](https://github.com/hibernate/hibernate-reactive/blob/1b0ec2be834bcdeadd8106dc560514e10b45548d/hibernate-reactive-core/src/main/java/org/hibernate/reactive/engine/jdbc/env/internal/ReactiveMutationExecutor.java#L60C32-L60C67) that returns a `voidFuture()` which does not execute `merge ......` commands and the select query's are empty.

I still don't know enough about this MutationExecutor framework to move toward a fix.

**Comment by DavideD** [comment]
It seems that we need to replace the `voidFuture()` with a reactive version of [AbstractMutationExecutero#performNonBatchedMutation](https://github.com/hibernate/hibernate-orm/blob/8df6d39b9739ca4476977817c33cff941896e123/hibernate-core/src/main/java/org/hibernate/engine/jdbc/mutation/internal/AbstractMutationExecutor.java#L79)

**Comment by DavideD** [comment]
Ah no, sorry.... I confused the two methods

**Comment by blafond** [comment]
@DavideD
Pushed latest: -- see: https://github.com/blafond/hibernate-reactive/tree/upsert-mysql-1768
- I was able to fix the `performUpdate()` and now the test runs for all DB's but ORACLE
- I almost have the `performDelete()` method working, but not sure if I set up the [test](https://github.com/blafond/hibernate-reactive/blob/e45383eda52f2ce403b119e785aab44b5ea79fec/hibernate-reactive-core/src/test/java/org/hibernate/reactive/UpsertTest.java#L158) for it correctly. It's currently failing and I've commented out the test : `testStageUpsertWithDelete()`.  The `delete` SQL is executed but there's an exception happening in the vertx client.

**Comment by DavideD** [comment]
The test seems correct, but I think you've copied the parameter binding from the update. The logic in ORM is quite different though, there is a `bindKeyValues` in `OptionalTableUpdateOperation` that does something else.

There are several `.thenAccept( v -> voidFuture() )` that should be `.thenCompose(CompletionStages::voidFuture)`

**Comment by blafond** [comment]
Pushed latest changes again to: https://github.com/blafond/hibernate-reactive/commit/b5ec0922a9cef3dad2272f0fa3a782e5ccb50b40

- Added another override in: `ReactiveStandardDialectResolver` to intercept/override the oracle translator with `ReactiveOracleSqlAstTranslator`.  This allowed the logic to set the Table alias correctly and fix the SQL error
