### ISSUE TITLE
Vertx Pgclient AWS Aurora Postgres

### ISSUE THREAD

**Issue by coder-github578** [hibernate/hibernate-reactive#2011]
I was trying out the simple example from below to connect to AWS Aurora Postgress.

https://github.com/hibernate/hibernate-reactive/tree/main/examples/session-example

However i am facing the below error.

io.vertx.pgclient.PgException: FATAL: pg_hba.conf rejects connection for host ... no encryption (28000)

**Comment by DavideD** [comment]
I'm not familiar with the AWS Aurora, but it seems you need to configure the Vert.x client with encryption.

Maybe this discussion can come in handy: https://github.com/hibernate/hibernate-reactive/issues/1108#issuecomment-1959543122

And this is the issue with an example on how to pass a Vert.x client with a custom configuration: https://github.com/hibernate/hibernate-reactive/issues/1866

I'm closing this issue because I don't think there something to do in Hibernate Reactive, but feel free to comment more if you have more questions.

**Comment by coder-github578** [comment]
Is there a way to pass the PgClientPoolConfiguration to Hibernate Mutiny Session Factory. We want to use the sessionfactory methods. Any kind of example would be nice

**Comment by coder-github578** [comment]
Thanks David It helped

**Comment by DavideD** [comment]
I don't know what you mean by using the SessionFactory methods.

Once you have your custom `PgClientPoolConfiguration`, like in the example, you can set the property `hibernate.vertx.pool.configuration_class` to the class path, for example `org.hibernate.example.PgClientPoolConfiguration`

As an alternative, `PgClientPoolConfiguration` implements the service `SqlClientPoolConfiguration`.
So you can register it following the example here: https://hibernate.org/reactive/documentation/2.4/reference/html_single/#_vert_x_instance_service

You only have to replace `VertxInstance` with `SqlClientPoolConfiguration`
