### ISSUE TITLE
Ability to map to the Postgresql type timestamptz

### ISSUE THREAD

**Issue by Sanne** [hibernate/hibernate-reactive#285]
Relaying this report from Quarkus:
https://github.com/quarkusio/quarkus/issues/10768

**Comment by gavinking** [comment]
Well, I'm not sure quite how much of a bug this is. Hibernate 5 simply doesn't have support for `OffsetDateTime`. (This was one of the things I added recently to Hibernate 6.)

So AFAICT, the only real question here is whether the Vert.x client should transparently convert a `LocalDateTime` to a `timestamptz` column. Perhaps it should, since the JDBC driver does do that, I think.

But that wouldn't be a change to Hibernate Reactive, but to the Vert.x driver.

So can I close this please?

**Comment by Sanne** [comment]
@gavinking IMO you're free to consider this low priority and park it for the next seaon, but I still think we should "own" the limitation, to track it and make sure stuff gets improved.. even if it needs ORM/classic changes and/or vertx.

**Comment by gavinking** [comment]
I disagree. If you think it's important, I think you should open an issue against the Vert.x client. If I'm not mistaken, there's no change we could reasonably make to HR that would solve this problem, since in general we don't know the database column types.

**Comment by gavinking** [comment]
(And if we need support for timezones in H5, we need to backport my H6 work, which affects quite a few bits of Hibernate, IIRC, but to be clear I don't think we need it.)

**Comment by Sanne** [comment]
Ok, let's close it then.

Just to clarify, the reason I suspect we'll eventually need some changes in HR is that if we were to patch ORM5 to support something like this, we'd need the capability to be opt-in: we don't want to break existing schema expectations in ORM5.

**Comment by gavinking** [comment]
Well the reason I don't think we need to backport this is that apart from one database (forget which, but it's not postgres) the `time stamp with time zone` type is a lie. This `timestamptz` thing doesn't actually store any time zone at all, it actually stores the time in UTC.

So in practice, I think `LocalDateTime` is the arguably most correct mapping here.
