### ISSUE TITLE
example model should have getters+setters

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#382]
I hate 'em, but the truth is that outside of Quarkus they're still a requirement, so we shouldn't mislead people to think they're not.

**Comment by gavinking** [comment]
@FroMage @Sanne am I right in understanding that in Quarkus, you simply don't need getters and setters, even when you're *not* using Panache?

**Comment by Sanne** [comment]
Hibernate ORM does have an enhancement option to not need accessors, it's called "extended enhancement" as it actually enhances the application code (not just the entities).

Within Quarkus we don't actually enable this option though, as Panache is doing a similar, but more advanced operation.

I guess I'm not sure of what we should be doing for an Quarkus+Hibernate user who doesn't have Panache as well - maybe enable it? The problem is that I don't fully trust it, for example it does assume that all code accessing the entities is part of the application code that we're enhancing (and not hiding into a 3rd party jar which we have as a dependency).

**Comment by Sanne** [comment]
BTW all most common use cases should work with plain ORM even without any enhancement. It's really more of an optimisation to track dirty entities efficiently.

**Comment by gavinking** [comment]
>  The problem is that I don't fully trust it, for example it does assume that all code accessing the entities is part of the application code that we're enhancing (and not hiding into a 3rd party jar which we have as a dependency).

Well I don't see how a third-party jar could possibly have been compiled against the user's program.

> BTW all most common use cases should work with plain ORM even without any enhancement. It's really more of an optimisation to track dirty entities efficiently.

The problem I'm concerned with here is external access to fields, without an intermediating getter/setter. It would be nice to be able to let people do what they can do in Panache, but our proxies prevent that.

**Comment by gavinking** [comment]
> maybe enable it?

Precisely *how* does one enable that?

**Comment by Sanne** [comment]
> Precisely how does one enable that?

Depends on what tool you're using to enhance the application. The maven plugin? Gradle?
 - https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#BytecodeEnhancement-enhancement-gradle

Programmatically it looks like:
 - https://github.com/quarkusio/quarkus/blob/7528eadb871badc9130ebcbbad04942ad146f40e/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateEntityEnhancer.java#L49-L63

> Well I don't see how a third-party jar could possibly have been compiled against the user's program.

Both the entities and the third-party business logic could be a dependency of the user code. It's solvable, but we'd need to analyze all bytecode (including all dependencies), which isn't being done today, I believe because of the performance hit it would have.

**Comment by gavinking** [comment]
>  Gradle?

Gradle.

But I don't see which of those three settings is the relevant one to intercept access from client code.

> Both the entities and the third-party business logic could be a dependency of the user code. It's solvable, but we'd need to analyze all bytecode (including all dependencies), which isn't being done today, I believe because of the performance hit it would have.

Well I think you're thinking too big. I think we could get a long way by:

- just handling access from within the same module, and
- letting the user explicitly list other modules which should be enhanced.

I don't think it's necessary to go off analyzing bytecode of all dependencies.
