### ISSUE TITLE
ReactiveStreams and Java 9 Flow API support

### ISSUE THREAD

**Issue by hantsy** [hibernate/hibernate-reactive#53]
Please add ReactiveStreams(rxjava2, reactor, MP ReactiveStreams etc)and Java 9 Flow API support.

it could be designed like the `.rx()` method of JAXRS client, provide variants to  `openRxSession(<accept a impl type>)`.

**Comment by gavinking** [comment]
@hantsy we definitely want to supporting other options than just `CompletionStage` but I'm going to delegate thinking about precisely which ones we support to people like @cescoffier and @FroMage and @emmanuelbernard.

My only suggestion is that I guess we could have multiple `RxSession` interfaces in different packages, and you could choose which one to `unwrap()`.

(A tangential issue is that we also need to support reactive database drivers other than the ones Vert.x provides.)

**Comment by emmanuelbernard** [comment]
That is something we need to discuss. if we go for Mutiny CC @cescoffier instead of CompletionStage, then Mutiny has bridges tot he other types and is an implementation of ReactiveStreams (for Publisher at least).

**Comment by gavinking** [comment]
Note that this is now a *very* easy thing for a user to contribute.

**Comment by cescoffier** [comment]
I agree with @emmanuelbernard :-)

**Comment by gavinking** [comment]
@cescoffier I already implemented a Mutiny-based API. It's documented in the readme and in the example program.

**Comment by cescoffier** [comment]
Cool! I will have a look!

**Comment by gavinking** [comment]
> Mutiny ... is an implementation of ReactiveStreams 

Alright, so from what I can see here:

<https://smallrye.io/smallrye-mutiny/>

The `Mutiny` API does already let people easily use Hibernate Reactive with other reactive streams implementations.

> Java 9 Flow API support

I don't know anything at all about this, but it also seems to be ReactiveStreams, so perhaps that's covered too. Anyway, we're targeting Java 8 for good reasons so we can't do anything specific with this API right now.

Look, I'm going to close this issue, since it's simply a bit too open ended.

Once someone has some real concrete use-case-driven experience, they can open new issues to request specific new APIs.

Right now I can't see what code I could possibly write that would let me mark this issue as "done". (Or rather, I probably already wrote the code when I added `Mutiny`.)
