### ISSUE TITLE
Should we test the Session.Mutiny API?

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#583]
There are some concerns about the build getting slower because we are adding tests that are not necessary.
The main problem seems to by the `Session.Mutiny` API.
I've decided to create an issue here because I prefer to have single place where to discuss it.

Possibly in a constructive way.

The implementation of the Mutiny API is a relatively simple wrapper around a common implementation of the Session API.
Still, at first glance, I don't personally feel comfortable not testing it.

Here's a list of the reasons we might not need to test the Mutiny API and some possible counter arguments:

* **Underneath, it wraps the same implementation as the Stage API**
   It's true that we basically convert the results from the CompletionStage to a Uni but Mutiny does a lot of magic under the hood and while this has not been a problem for us so far, on Quarkus we have issues appearing only when users use one type of API or the other. Granted that it's a more complicated scenario. Hibernate Reactive can still make sure that there aren't any basic mistakes or regressions. 

* **A minor mistake will double the number of test failures.**
  I guess this is a good point but I always had this issue with hibernate, it mostly depends from the type of error.  For example, if something is wrong with the support of  `@ElementCollection`, all the tests using the annotation will fail. If the error is related to `@OrderColumn` only the test using both annotation will fail. It's because we don't really have `unit` testing. On the other hand if  you fix a test, all the others will work as well.

* **We should write tests that breaks the code, there is no point in testing something that we already know is working**
   Well, not really. We also need to make sure that what's working now will continue to work.

* **The test suite will become slower and slower**
  Of course, a build without tests will always be faster. But I don't know if I like the idea of the trade off we are willing to accept.
  We could move the tests with Mutiny in a different module and enable only when required, for example on CI.
  It's also possible to filter the tests run while working on a specific issue, there is no need to run the complete test suite
  all the time.

I think these are the main points.

**Comment by gavinking** [comment]
> I don't personally feel comfortable not testing it.

_Nobody_ has said that we shouldn't test the Mutiny API, so that's silly.

Indeed, we already test all its operations. That's what `MutinySessionTest` is for. (Blame says I'm the author of that class, so it can't possibly be that I don't think we should have tests for the Mutiny API.)

The argument is that _we don't need two tests for every single feature of Hibernate Reactive_. It's *perfectly sufficient* to have one test for each, some of which use `Stage.Session`, some of which use `Mutiny.Session`.

> We also need to make sure that what's working now will continue to work.

There's no reasonable scenario in which we would start forking bits of the internal implementation of Hibernate Reactive, introducing one implementation for Mutiny and one implementation for `CompletionStage`. So this is also silly. One of `Stage.Session` or `Mutiny.Session` is *always* going to be a simple wrapper around whatever is underneath.

But, of course if that *does* ever change (it won't), on that day I will be in 100% agreement that we need two tests for every feature.

But you've ignored the main reason I cited for not having two tests for every feature: **code duplication**. Twice as much test code makes the test suite twice as hard to maintain.

**Comment by DavideD** [comment]
> _Nobody_ has said that we shouldn't test the Mutiny API, so that's silly.

Yes, I got it, sorry. My choice of words wasn't exactly the best.

**Comment by DavideD** [comment]
> But you've ignored the main reason I cited for not having two tests for every feature: code duplication. Twice as much test code makes the test suite twice as hard to maintain.

That's because I don't consider it code duplication. As I mentioned before, Mutiny hide a lot of complexity under the hood.
But I guess you are right when you say that we already testthe Mutiny API. Between the `MutinySessionTest` and the one we added with the other PRs we probabaly already have good coverage for most scenarios.

Adding new ones might not be that helpful after all.

**Comment by DavideD** [comment]
I would keep the tests that we have now and not add new one for the time being.

**Comment by DavideD** [comment]
I think we are on the same page about this issue now.
