### ISSUE TITLE
test @SqlInsert, @SqlUpdate, and @SqlDelete

### ISSUE THREAD

**Issue by gavinking** [hibernate/hibernate-reactive#592]
The `@SqlInsert`, `@SqlUpdate`, and `@SqlDelete` annotations let you specify custom SQL to use for entity CRUD. These almost certainly work already (though we have not tested them), except, perhaps, for stored procedures. Now, it doesn't look like Vert.x has any special API for callable statements, so maybe this just works too?

Anyway, we need to test all this just to be sure.

**Comment by gavinking** [comment]
I've added a test for regular DML (*not* stored procedures) and, as predicted, it's working in that case.

**Comment by gavinking** [comment]
@DavideD @blafond would one of you guys like to look into writing a version of `CustomSqlTest` that uses stored procedures?

Well, probably *two versions*, one for MySQL and one for Postgres.

**Comment by gavinking** [comment]
> one for MySQL and one for Postgres

Actually it's unclear from the docs if the Vert.x client supports stored process on Postgres. It *does* seem to support them on MySQL.

**Comment by DavideD** [comment]
@blafond would you like to have a look at this?

**Comment by blafond** [comment]
I've added some tests to my [stored-procedure-sql-592](https://github.com/blafond/hibernate-reactive/commits/stored-procedure-sql-592) branch

The commit is [here](https://github.com/blafond/hibernate-reactive/commit/7b37bf7dbfa7e5d54a8935d3112e84a68dd13458)

The @SqlInsert and @SqlUpdate work, but the @SqlDelete case is failing because it ```deleted``` is still null.  ```record.remove(id)``` is not resulting in the timestamp being applied.  Note I can execute it manually in psql  ```SELECT PROC_DELETE_RECORD(1);``` and it works.

**Comment by DavideD** [comment]
It's a problem with the test. I've commented on the commit

**Comment by gavinking** [comment]
I can close this now, correct?

Thanks folks.
