### ISSUE TITLE
Add licenses

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#60]
We need to add a license to all classes similar to the one we have for the other hibernate projects

**Comment by Sanne** [comment]
I'd suggest to enable checkstyle for this, with a single rule: just check the headers?

**Comment by gavinking** [comment]
Oh gawd no, please no checkstyle. It's evil incarnate.

I really don't want to have to deal with failing CI builds because someone accidently removed a newline at the end of the file.

**Comment by Sanne** [comment]
Well you can customize it :)

We can set it up to only check that the expected copyright header is in place

**Comment by Sanne** [comment]
P.S. we can also set it to just warn rather than fail the build - not sure if people will pay attention in that case though..

**Comment by gavinking** [comment]
By the way, I just checked, and none of the code in the Quarkus repo has headers, so I don't think we need them either.

**Comment by Sanne** [comment]
@gavinking you'd not have needed them if you'd have opted for ASL2 :P

**Comment by gavinking** [comment]
AFAIK we don't need them at all. A license file in the repo and in the dist is plenty.

**Comment by DavideD** [comment]
> P.S. we can also set it to just warn rather than fail the build - not sure if people will pay attention in that case though..

I don't like this, too easy to miss. If we need to add the license on the class it has to fail when the license is missing. In eclipse it's a template that add it automatically. I'm sure we can do something similar in Intellij

**Comment by gavinking** [comment]
>  If we need to add the license on the class it has to fail when the license is missing. 

Again, AFAIK we don't.

You put the license in the project root directory. That is the standard approach.

Adding headers to source files is just yet another thing that makes it harder to do work and creates problem for contributors.

**Comment by DavideD** [comment]
> Again, AFAIK we don't.

I haven said you are wrong. Shouldn't we check, though? 

> By the way, I just checked, and none of the code in the Quarkus repo has headers, so I don't think we need them either.

That's fine but this seem to me a legal problem (as far as I can tell). Is it enough to say: "they don't do it, so we won't either"?

> Adding headers to source files is just yet another thing that makes it harder to do work and creates problem for contributors.

We've been doing it in all the other Hibernate projects for years and doesn't cause any issue of this kind (we have templates ready). It's not something new.

**Comment by Sanne** [comment]
I've sent an email to Richard, you're all in CC - so let's wait for that.

**Comment by gavinking** [comment]
> If we need to add the license on the class it has to fail when the license is missing.

See this is precisely what cheeses me off about this sort of stuff. So there's a sort of soft _recommendation_ from legal that if we add these notices it's nice because we can make life easier for some sort of automated source code scanning tools that people might hypothetically use.

Which is fine. I'm OK with that.

But then somehow we get from that to it's an absolute hard requirement that EVERY SINGLE SOURCE FILE HAS TO HAVE COPYRIGHT!!!!!!! and if we find one single file that doesn't have it then we make the build fail and everyone has to drop what they're doing and immediately go and race off and fix it right now even though some of us were actually doing real work at the time.

Back in reality it's simply *not* a problem at all if a few files in the code base are missing a header, and it's 99% probable that nobody's running an automated source code scanning tool on our source code anyway.

But y'know, while we're making checkstyle nags, I think I'll make a checkstyle nag that fails the build every time you guys check in a file that doesn't have Javadoc on it. Something tells me you wouldn't like that. And you'd be right. And you know wanna know what is the only difference between license notices and Javadoc? 

That's right. *Javadoc is actually really useful and important.*

> We've been doing it in all the other Hibernate projects for years and doesn't cause any issue of this kind

Well, wait, how do you think I even know that Hibernate ORM has a checkstyle build that fails when there's a missing header? Because I've had to deal with its shit. And it's really a pain.

First of all, checkstyle is incredibly dog slow. Second it complains about totally idiotic things like missing newlines at the end of the file. And please don't try to tell me this is a nonissue because it's an issue right now in Hibernate ORM that I had to deal with when I was working on Hibernate 6.

And, I mean, look, I already feel like I spend more time dealing with gradle and git than I spend actually making things in Java, so I would really prefer to not add another slow step to the build.

Finally: outside contributors don't have their IDEs set up with exactly the same templates and stuff that you have in your IDE. (And that's especially the case since you insist that we're not allowed to check IntelliJ/Eclipse metadata into git.)

So anyway, if we have to do this then at least please be sensible about it and treat missing copyright noticed in just the same way you already treat missing Javadoc.

**Comment by gavinking** [comment]
So in summary. I support adding checkstyle _iff_ it will prevent you from checking in code without Javadoc 🤭

**Comment by Sanne** [comment]
I agree with your concerns @gavinking , we don't want to waste time on pesky tooling. ll propose a solution which doesn't use checkstyle and still lets us have the headers consistently and hopefully at minimal hassle.

**Comment by Sanne** [comment]
This was fixed via #191

**Comment by DavideD** [comment]
Thanks!
