### ISSUE TITLE
Test the DB2 reactive client

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#64]
https://github.com/eclipse-vertx/vertx-sql-client/tree/master/vertx-db2-client

**Comment by aguibert** [comment]
I will look into this once either the DB2 client gets backported to Vertx 3.9 or HibernateRX upgrades to Vertx 4.0 (but probably will be the former)

**Comment by aguibert** [comment]
After temporarily rebasing on Vertx 4 locally (in order to be able to use the DB2 module) I was able to get the basic insert+find scenario working, found/fixed a few bugs along the way too, so this gives me good confidence that once I backport the DB2 client to Vertx 3 it will work with Hibernate RX initially

**Comment by gavinking** [comment]
@aguibert Any chance we could get this into the first release? I would *love* to have DB2 support!

**Comment by aguibert** [comment]
Me too! Do you have an ETA on first release @gavinking? 

I will have to backport the DB2 driver to Vertx 3.X (which is non-trivial I've been told). It will also require me to keep 3.X and 4.X in sync after I backport, so I am trying to stabilize it as much as possible before I do that split.

**Comment by gavinking** [comment]
> Me too! Do you have an ETA on first release @gavinking?

Ask @emmanuelbernard.

**Comment by emmanuelbernard** [comment]
@aguibert ideally Quarkus 1.5 which would be a month or so after 1.4 is out. So you have a month in front of you.
