### ISSUE TITLE
Add CockroachDB to the list of of available databases

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#642]
Thanks to @conorfarrell-coats, we learnt that we could support CockroachDB as well:
https://github.com/hibernate/hibernate-reactive/pull/640

We should add it to our test suite

**Comment by Sanne** [comment]
N.B. CockroachDB is extremely slow (by design) on performing schema changes, I assume because it requires a strong consensus protocol, which made it a pain to test with in Hibernate ORM as our testsuite by changes the schema very frequently (almost for each unit test).

I've long wished for the ORM core code to use a unified schema; that would require a very extensive refactoring though. I wonder if you could already take this into account in Hibernate Reactive.

I'm not asking to refactor all tests like that as a pre-requisite to support CockroachDB, but to plan for some form of grouping of tests which could share the same schema, so as to evolve in the right direction.

**Comment by DavideD** [comment]
I think it's too late for that

**Comment by DavideD** [comment]
> I think it's too late for that

I mean, we already have a lot of of tests. We could start to think about it, I guess.

**Comment by Sanne** [comment]
It's never too late :)

It's hard in ORM because it has 10,000+ integration tests; I'm sure it's feasible here - and as I suggested I'm not asking to change all existing tests: this is about speed of execution so even if some tests are slow that's ok, let's just make sure it doesn't grow to unbearable levels by trying to group future tests.
