### ISSUE TITLE
UTCTest.testOffsetDateTime() test failure locally

### ISSUE THREAD

**Issue by blafond** [hibernate/hibernate-reactive#901]
running this test locally by itself or with a local build throws the same exception:
```
Not equals : -05:00 != Z
java.lang.AssertionError: Not equals : -05:00 != Z
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:362)
	at io.vertx.ext.unit.impl.TestContextImpl.assertEquals(TestContextImpl.java:258)
	at io.vertx.ext.unit.impl.TestContextImpl.assertEquals(TestContextImpl.java:245)
	at org.hibernate.reactive.UTCTest.lambda$testOffsetDateTime$5(UTCTest.java:118)
	at org.hibernate.reactive.UTCTest.lambda$testField$10(UTCTest.java:161)
```

It doesn't appear to fail in the CI builds.

Note I'm in the America/Chicago time-zone with an offset of ` -05:00`

**Comment by blafond** [comment]
@DavideD I don't understand the use the constant: `ZoneOffset.UTC` in the assertion that's failing?

**Comment by DavideD** [comment]
Which assertion is failing?

**Comment by blafond** [comment]
line 118:  `context.assertEquals( entity.offsetDateTime.getOffset(), ZoneOffset.UTC );`

**Comment by DavideD** [comment]
[In the configuration of the test](https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/test/java/org/hibernate/reactive/UTCTest.java#L40) we set the property `hibernate.jdbc.time_zone` to `UTC`.

So the timezone of the date should be set to `UTC` before saving it to the database.
This is what I see when I debug.
You can add a break point here: https://github.com/hibernate/hibernate-reactive/blob/main/hibernate-reactive-core/src/main/java/org/hibernate/reactive/adaptor/impl/PreparedStatementAdaptor.java#L172

The `Calendar` parameter, used to set the timezone, should be set to `UTC`.

We also set the time zone to UTC when we read the value in ResultSetAdaptor (as far as I can see). So I'm not sure why you have a different time zone.

**Comment by DavideD** [comment]
OK, I can recreate the error if I change the time zone on my machine. As an experiment, I think it will work if you set the time zone  on your pc to UTC

**Comment by DavideD** [comment]
I think this is a bug in ORM. When it converts the Timestamp to the OffsetDateTime, it uses the system default time zone instead of the one we set with the property.

Could you create a test for ORM and ask the team, please?
FIY: [This is the code that's setting the wrong time zone](https://github.com/hibernate/hibernate-orm/blob/0325cd632a704ff82b789544bfefb7e11ac97cd9/hibernate-core/src/main/java/org/hibernate/type/descriptor/java/OffsetDateTimeJavaDescriptor.java#L127).

**Comment by DavideD** [comment]
I'm susprised nobody else had this failure before, I think I'm the only one in the UTC zone

**Comment by gavinking** [comment]
Hrm. But if you're using `OffsetDateTime` it's because you want the *database* to decide the timezone, right? unless I've forgotten something, we should be ignoring `hibernate.jdbc.time_zone` in that case, shouldn't we?

Trying to remember how all that stuff worked...

**Comment by gavinking** [comment]
Yeah, I mean, we made `hibernate.jdbc.time_zone` work (sorta) for `Time` and `Timestamp`, which are types which don't carry a timezone. But `OffsetDateTime` is a whole different kettle of fish. An `OffsetDateTime` already _has_ a welldefined timezone. We shouldn't just overwrite it.

**Comment by DavideD** [comment]
Would it matter in this case? As far as I understand, during the conversion from `Timestamp`  to `OffsetDateTime` the time zone is always set to the system default. No matter what value we used originally.

**Comment by gavinking** [comment]
> during the conversion from `Timestamp` to `OffsetDateTime` the time zone is always set to the system default. No matter what value we used originally.

Well that sounds definitely-wrong.

OTOH, I recall that H5 never really had proper support for `timestamp with timezone` (I added it in H6) so this behavior might be because of that.

I can tell you what should be the correct behavior in H6. But not in H5, which is a bit of a black box in this area as far as I'm concerned.

**Comment by DavideD** [comment]
> I can tell you what should be the correct behavior in H6

OK, what should be the correct behaviour?

It's a bit weird but I'm ok saying that Hibernate Reactive will always use the system default timezone if that's what's happening. As long as we are clear with the user. They can always store it using a custom user type if that doesn't work for them.

**Comment by gavinking** [comment]
> OK, what should be the correct behaviour?

Well the timezone should be preserved across all operations.

But I'm pretty sure that doesn't work in H5, because I did rather a lot of work _to make it work_ in H6.

**Comment by DavideD** [comment]
> Well the timezone should be preserved across all operations.

your initial sentence sounded much more mysterious :-D

**Comment by DavideD** [comment]
I would say, let's update the tests so that it checks that the time zone is the system default, add a note to the documentation and close this issue

**Comment by gbadner** [comment]
BTW, when I run the test, I get the following:
```
Not equals : -07:00 != Z
java.lang.AssertionError: Not equals : -07:00 != Z
```
In case you haven't figured this out yet, I'm posting the following stuff...

In order to get consistent results, I think you will have to set the default JVM time zone on the test, similar to what is done in the ORM test for `OffsetDateTime`, [OffsetDateTimeTest#testRetrievingEntityByOffsetDateTime](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/test/java/org/hibernate/test/type/OffsetDateTimeTest.java).

Notice that in the superclass, [`AbstractJavaTimeTypeTest`](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/test/java/org/hibernate/test/type/AbstractJavaTimeTypeTest.java), the default time zone is set for each test by [`AbstractJavaTimeTypeTest#withDefaultTimeZone`](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/test/java/org/hibernate/test/type/AbstractJavaTimeTypeTest.java#L190-L191), then reset to the original time zone in the `finally` block at the end.

I am relying on my memory about this, but I *think* that `hibernate.jdbc.time_zone` is only used for converting a value from the default JVM timezone to the JDBC timezone for storing in the database, and for converting the value returned from the database from the JDBC time zone to the JVM default time zone.

I could be totally wrong about that though.

I think that @yrodiere would be the best person to ask about this.

**Comment by yrodiere** [comment]
> I think that @yrodiere would be the best person to ask about this.

Not sure I'm the best for that (the people who originally implemented this stuff would know best) but I can try to answer, provided there's a question :)

> I am relying on my memory about this, but I think that `hibernate.jdbc.time_zone` is only used for converting a value from the default JVM timezone to the JDBC timezone for storing in the database, and for converting the value returned from the database from the JDBC time zone to the JVM default time zone.

That's right, but the purpose of this property is actually to prevent the JDBC driver from relying on the JVM default timezone. So, depending on how reactive drivers work, it might be relevant in Hibernate Reactive as well.

For reference:

* [Reference documentation](https://docs.jboss.org/hibernate/orm/5.5/userguide/html_single/Hibernate_User_Guide.html#basic-datetime-time-zone)
* [Relevant blog post](https://in.relation.to/2016/09/12/jdbc-time-zone-configuration-property/)

**Comment by DavideD** [comment]
I don't think the issue here is about the `hibernate.jdbc.time_zone`. I might have a better look at it later but it seems to work as expected in Hibernate Reactive.
The problem here is to define what happens when we save a type with a time zone and clarify that in the documentation. It seems to me that the time zone is always returned using the system default.

Unless we want to test that the built-in type works for every possible time zone, I think we could close this issue applying one of these two fixes:
1. Set the default time zone to UTC at the beginning of the test that's failing, or
2. Check that the time zone returned when loading the entity is the system time zone (and not necessarily UTC)

I think I prefer option 2 a bit better, because if somebody runs the test in a time zone that causes issues, the test will fail.

@blafond Could you have  a look at this and suggest a fix, please? You could also check what happens with ORM when you run the same test that's failing for HR.

**Comment by blafond** [comment]
@DavideD I was able to reproduce the error using ORM session.

I can make both **1.** and **2.** work, but for the latter I came up with is this assertion:
```
	context.assertEquals(
			entity.offsetDateTime.toZonedDateTime().getZone(),
			OffsetDateTime.now( ZoneId.systemDefault() ).toZonedDateTime().getZone()
	);
```

**Comment by DavideD** [comment]
Please, when you send the PR, add a comment in the test so that we don't forget why we need this extra logic
