### ISSUE TITLE
Use JPA repositories with hibernate-reactive.

### ISSUE THREAD

**Issue by saksham-kakkar** [hibernate/hibernate-reactive#920]
Hi, Is there a way to use CrudRepository/JpaRepository, or other similar repositories with hibernate-reactive, spring boot?

**Comment by gavinking** [comment]
If you mean the Spring stuff, then no. Hibernate Reactive has different signatures for persistence operations, so that's just not possible. (Though personally I have never seen what value DAOs/"repositories" add anyway, and would never use them even with regular Hibernate.)

However, if you're using Quarkus, you could try using Panache Reactive, which is a different approach, not the DAO pattern, more like the active record pattern.
