### ISSUE TITLE
Support Vertx Future

### ISSUE THREAD

**Issue by codingxu97** [hibernate/hibernate-reactive#996]
Future in Vertx 4 was useful enough, I thought that it was better to use official component than others IMHO.
```
@Override
public <T> T unwrap(Class<T> type) {
	if ( type.isAssignableFrom(Stage.SessionFactory.class) ) {
		return type.cast( new StageSessionFactoryImpl( this ) );
	}
	if ( type.isAssignableFrom(Mutiny.SessionFactory.class) ) {
		return type.cast( new MutinySessionFactoryImpl( this ) );
	}
	return super.unwrap(type);
}
```

**Comment by DavideD** [comment]
Sounds like a nice idea though :-)

**Comment by codingxu97** [comment]
Maybe I was used to using Vert.x Future, I will try to add a Test before send a draft PR.

**Comment by DavideD** [comment]
@codingxu97 Basically, we need a compelling use case.

That's because once we add something to the project we have to maintain it.

**Comment by codingxu97** [comment]
Hi, @DavideD !

I've thought a lot about this issue, and made some attempts.

The projects were only based on Vert.x and other lightweight library in our team, Vert.x Future was enough for us to finish our project, so we didn't use ```Mutiny``` or other Reactive library.

But, we have to use ```Mutiny``` if we choose ```Hibernate Reactive```, There would be two different Reactive code styles in our project. it seems messy, and might be difficult to manage. It would bring huge workload, if we switch all code to ```Mutiny```, even a lot of potential bugs.

On the other hand, Class ```Future``` was in ```Vert.x core``` Library, so it did't have to import a new jar in order to implement this.

These were some of my humble opinion, thanks!

**Comment by DavideD** [comment]
You don't have to use Mutiny, you could use `CompletionStage`. Without changing Hibernate Reactive, you need a facade for `Stage.SessionFactory` and `Stage.Session` that internally delegate to a `FutureSessionFactory` and `FutureSession`.

It would actually be easier to do in your project, because you can only delegate the methods that you need. If we add it to Hibernate Reactive, we need to add a lot more code.
Ideally, it should be possible to register the new interfaces without changing the code base of Hibernate Reactive, but I haven't actually tried and I don't know if it works in practice.

This would be equivalent to what we would do in Hibernate Reactive anyway, because internally we use `CompletionStage`.
You can see this in [MutinySessionImpl](https://github.com/hibernate/hibernate-reactive/blob/41f6e35f12088bdc562f82e7088ef54abe75db6e/hibernate-reactive-core/src/main/java/org/hibernate/reactive/mutiny/impl/MutinySessionImpl.java#L56): we have a delegate returning `CompletionStage` and we convert the result to `Uni`.

The reason we are using `CompletionStage` internally is because we didn't want to be bound to a particular library.
The reason we suggest using Mutiny is because we think the API is better and easier to use.
Maybe we should make the dependency to Mutiny optional.

**Comment by DavideD** [comment]
I'm going to close this issue because I don't think we are going to do it.
But I've created https://github.com/hibernate/hibernate-reactive/issues/1200 that should address this one as well.
